module.exports = [
  // Technology & IT
  { name: "Software Engineer" },
  { name: "Frontend Developer" },
  { name: "Backend Developer" },
  { name: "Full Stack Developer" },
  { name: "Mobile App Developer" },
  { name: "DevOps Engineer" },
  { name: "Cloud Engineer" },
  { name: "Data Scientist" },
  { name: "Data Analyst" },
  { name: "Machine Learning Engineer" },
  { name: "AI Engineer" },
  { name: "Blockchain Developer" },
  { name: "Cybersecurity Analyst" },
  { name: "IT Support Specialist" },
  { name: "System Administrator" },
  { name: "Network Engineer" },
  { name: "QA Engineer" },
  { name: "UI/UX Designer" },
  { name: "Product Manager" },
  { name: "Technical Project Manager" },

  // Finance & Business
  { name: "Accountant" },
  { name: "Financial Analyst" },
  { name: "Investment Banker" },
  { name: "Auditor" },
  { name: "Tax Consultant" },
  { name: "Business Analyst" },
  { name: "Operations Manager" },
  { name: "HR Manager" },
  { name: "Recruiter" },
  { name: "Administrative Assistant" },
  { name: "Office Manager" },

  // Sales & Marketing
  { name: "Sales Executive" },
  { name: "Sales Manager" },
  { name: "Business Development Manager" },
  { name: "Digital Marketing Specialist" },
  { name: "SEO Specialist" },
  { name: "Content Writer" },
  { name: "Social Media Manager" },
  { name: "Marketing Manager" },
  { name: "Brand Manager" },
  { name: "Customer Support Executive" },
  { name: "Call Center Agent" },

  // Healthcare
  { name: "Doctor" },
  { name: "Surgeon" },
  { name: "Nurse" },
  { name: "Pharmacist" },
  { name: "Medical Laboratory Technician" },
  { name: "Radiologist" },
  { name: "Physiotherapist" },
  { name: "Psychologist" },
  { name: "Healthcare Administrator" },
  { name: "Dentist" },

  // Education
  { name: "Teacher" },
  { name: "Professor" },
  { name: "Lecturer" },
  { name: "Research Assistant" },
  { name: "Principal" },
  { name: "Tutor" },
  { name: "Instructional Designer" },
  { name: "Academic Coordinator" },

  // Skilled Trades
  { name: "Electrician" },
  { name: "Plumber" },
  { name: "Carpenter" },
  { name: "Mechanic" },
  { name: "Welder" },
  { name: "Technician" },
  { name: "Driver" },
  { name: "Construction Worker" },
  { name: "Machine Operator" },

  // Creative & Media
  { name: "Graphic Designer" },
  { name: "Video Editor" },
  { name: "Photographer" },
  { name: "Animator" },
  { name: "Journalist" },
  { name: "Copywriter" },
  { name: "Public Relations Specialist" },
  { name: "Event Planner" },
  { name: "Fashion Designer" },
  { name: "Interior Designer" },

  // Others
  { name: "Lawyer" },
  { name: "Paralegal" },
  { name: "Police Officer" },
  { name: "Soldier" },
  { name: "Chef" },
  { name: "Waiter" },
  { name: "Retail Store Manager" },
  { name: "Cashier" },
  { name: "Flight Attendant" },
  { name: "Pilot" },
  { name: "Civil Engineer" },
  { name: "Mechanical Engineer" },
  { name: "Electrical Engineer" },
  { name: "Chemical Engineer" },
  { name: "Architect" },
];
